
chains:
  ETH:
    networks:
      SEPOLIA:
        testnet: true
        rpcUrls: 
          - url: https://rpc-sepolia.rockx.com
      GOERLI:
        testnet: true
        rpcUrls: 
          - url: https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161	
            name: infura_custom_goerli
  TRX:
    networks:
      NILE:
        testnet: true
        rpcUrls:
          - url: https://nile.trongrid.io/jsonrpc
  BNB:
    networks:
      TESTNET:
        testnet: true
        rpcUrls:
          - url: https://rpc.ankr.com/bsc_testnet_chapel


